language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
env:
  global:
    secure: Xjn7U4IM5z5th0eTYv7N8gpCST27V64ypglkVQX0WNoH4NQlH1LwbGrhcXFo2r58FFIkjo6MsS5QxJdvjxrbL8IgYqBBU1GBds1zpr9k8ltLaSrHMCobgpvq/+RHLFODlZ0z9nrq/2emaHlGVxIOMkbef+LsJ1IgdvzDKcjm5md8wjcYLjpyzOL5wlbRBwgFmorurZ+Ht/ljM6zXBPF7bKfChxuZgyUlIlSQWX8SJJ+nYtZEqHfjp/Kq3HqJZwuHMVNUGThQEoAm9fiVES759tGueo5UmiENPqn8WTST41LAqo49OCWbecDM5n0x0xbDkT3ULES8eptLUjodidpPm1io3xFw2IPEcEiBQHQ+SaHzbvXYxwnExqoBnZbUOO00S8ebTpAYJMHVm3JSFMrpJhxSZ/S0Sy6UH5VcCEvVMUt90JWdHa/ehuJPcxGZpjcbJ4irHRhD/BCwexmMgZVkA4f3UZdjjk+PMtu76Z3PEDcmYXZvNGm9e4GM1vs2/Y+19k2e3V5341lbVxwrcS6VAR7L5j8OOrVLkqpzvwgcH4C439wtiJg5oMsAbzI9YXaP/mmNM5FIjEeybhUmC+5GQRvQiBqaeSDFG6VBxMEU6v38jZi+Ar/aBK9l1p71ix0enPhoTAHz5/AC1tM+1YiHxwCmL7mZZsiuQ3rouGvm8u0=
before_install:
  - git config --global user.name "Kelly Heard"