# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Kelly Heard
tagline:             'Technology & Subject Matter Expert in Ecommerce'
description:         'Currently @Sitecore. Technology, Photography and More!'
url:                 http://heardk.github.io/
baseurl:             'heardk.github.io'
paginate:            5

# About/contact
author:
  name:              Kelly Heard
  url:               https://twitter.com/kellyheard
  email:             ''

# Custom vars
version:             1.0.0
