# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /blog/:title

# Setup
title:            'Kelly Heard'
tagline:          ''
description:      'Ecommerce, Technology, Photography & Life'
url:              'https://kellyheard.com/'
baseurl:          '/'
author:
  name:           'Kelly Heard'
  twitter:        'kellyheard'
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           #https://github.com/poole/hyde
exclude:          [example-content.md, Gemfile, Gemfile.lock, README.Hyde.md, Rakefile, .travis.yml, vendor]
gems:             [jekyll, jekyll-paginate, jekyll-archives, jekyll-seo-tag, pinboard, markaby, flickraw, airrecord, haml]

collections:
  notes:
    output: true
    permalink: /:collection/:path

jekyll-archives:
  enabled:
    - categories
  layout: 'category'
  permalinks:
    category: '/blog/category/:name/'