# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /blog/:title

# Setup
title:            'Kelly Heard'
tagline:          ''
description:      'Blog - Ecommerce, Technology, Photography & Life'
url:              https://kellyheard.com
baseurl:          /
author:
  name:           'Kelly Heard'
  twitter:        'kellyheard'
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           #https://github.com/poole/hyde
exclude:          [example-content.md, Gemfile, Gemfile.lock, README.Hyde.md, Rakefile, .travis.yml, vendor]
gems:             [jekyll, jekyll-paginate, jekyll-archives, jekyll-seo-tag, pinboard, markaby]

# jekyll-archive
# https://github.com/jekyll/jekyll-archives/tree/master/docs

# jekyll-seo-tag
# https://github.com/jekyll/jekyll-seo-tag

# Pinboard Gem
# http://www.rubydoc.info/gems/pinboard/1.0.0

# Rake Jekyll
# https://github.com/jirutka/rake-jekyll

jekyll-archives:
  enabled:
    - categories
  layout: 'category'
  permalinks:
    category: '/blog/category/:name/'