# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Kelly Heard
tagline:             'Technology & Subject Matter Expert in Ecommerce'
description:         'Technology & Subject Matter Expert in Ecommerce - Currently @Sitecore. \nTechnology, Photography and More!'
url:                 https://heardk.github.io/
baseurl:             https://heardk.github.io
paginate:            5

# About/contact
author:
  name:              Kelly Heard
  url:               https://twitter.com/kellyheard
  email:             ''

# Custom vars
version:             1.0.0
