title: Blog & Personal Site of Kelly Heard
author: Kelly Heard
email:
description: > # this means to ignore newlines until "show_exerpts:"
  Blog and Personal Site for Ottawa-based Product Manager in Ecommerce and Technology
plugins:
  - github-pages