# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /blog/:title

# Setup
title:            'Kelly Heard'
tagline:          ''
description:      'Product Manager, Ecommerce & Technology'
url:              'https://kellyheard.com/'
baseurl:          ''
author:
  name:           'Kelly Heard'
  twitter:        'kellyheard'
paginate:         8
exclude:          [Gemfile, Gemfile.lock, README.Hyde.md]
plugins:          [github-pages]