# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /blog/:title

# Setup
title:            'Kelly Heard'
tagline:          ''
description:      'Technology & Subject Matter Expert in Ecommerce - Currently @Sitecore. Technology, Photography and More!'
url:              https://kellyheard.com
baseurl:          /

author:
  name:           'Kelly Heard'
  url:            https://twitter.com/kellyheard

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           #https://github.com/poole/hyde
