# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /blog/:title

# Setup
title:            'Kelly Heard'
tagline:          ''
description:      'Product Manager, Ecommerce & Technology'
url:              'https://kellyheard.com/'
baseurl:          ''
author:
  name:           'Kelly Heard'
  twitter:        'kellyheard'
paginate:         8

# Custom vars
version:          2.1.0
github:
  repo:           #https://github.com/poole/hyde
exclude:          [example-content.md, Gemfile, Gemfile.lock, README.Hyde.md, Rakefile, .travis.yml, vendor]
plugins:          [github-pages]