url:              https://github-blog-heardk.c9users.io/
baseurl:          '/'
gems:             [jekyll-paginate, github-pages, jekyll-archives, jekyll-seo-tag, jekyll-admin]

# jekyll-archive
# https://github.com/jekyll/jekyll-archives/tree/master/docs

# jekyll-seo-tag
# https://github.com/jekyll/jekyll-seo-tag

# jekyll-admin
# https://github.com/jekyll/jekyll-admin